# Generated by Django 4.2.16 on 2024-10-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhotoCard",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("photo_name", models.CharField(max_length=128)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
