# Generated by Django 4.2.16 on 2024-10-15 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("photoCard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SellPhotoCardList",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.IntegerField()),
                ("fee", models.IntegerField()),
                ("status", models.BooleanField(default=False)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("renewal_date", models.DateTimeField(auto_now=True)),
                ("sold_date", models.DateTimeField(blank=True, null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "photo_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="photoCard.photocard",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
